# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SideWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.SongName = QtWidgets.QLabel(self.centralwidget)
        self.SongName.setObjectName("SongName")
        self.horizontalLayout.addWidget(self.SongName)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.SongSimilarity = QtWidgets.QLabel(self.centralwidget)
        self.SongSimilarity.setObjectName("SongSimilarity")
        self.horizontalLayout.addWidget(self.SongSimilarity)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.SongName_2 = QtWidgets.QLabel(self.centralwidget)
        self.SongName_2.setObjectName("SongName_2")
        self.horizontalLayout_2.addWidget(self.SongName_2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.SongSimilarity_2 = QtWidgets.QLabel(self.centralwidget)
        self.SongSimilarity_2.setObjectName("SongSimilarity_2")
        self.horizontalLayout_2.addWidget(self.SongSimilarity_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Song1Name = QtWidgets.QLabel(self.centralwidget)
        self.Song1Name.setObjectName("Song1Name")
        self.gridLayout.addWidget(self.Song1Name, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Feature1_1 = QtWidgets.QLabel(self.centralwidget)
        self.Feature1_1.setObjectName("Feature1_1")
        self.gridLayout.addWidget(self.Feature1_1, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Feature2_1 = QtWidgets.QLabel(self.centralwidget)
        self.Feature2_1.setObjectName("Feature2_1")
        self.gridLayout.addWidget(self.Feature2_1, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SecondSongName = QtWidgets.QLabel(self.centralwidget)
        self.SecondSongName.setObjectName("SecondSongName")
        self.verticalLayout_3.addWidget(self.SecondSongName)
        self.Feature1_2 = QtWidgets.QLabel(self.centralwidget)
        self.Feature1_2.setObjectName("Feature1_2")
        self.verticalLayout_3.addWidget(self.Feature1_2)
        self.Feature2_2 = QtWidgets.QLabel(self.centralwidget)
        self.Feature2_2.setObjectName("Feature2_2")
        self.verticalLayout_3.addWidget(self.Feature2_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "The Song is Similar to"))
        self.SongName.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "By"))
        self.SongSimilarity.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "The Song is Similar to"))
        self.SongName_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "By"))
        self.SongSimilarity_2.setText(_translate("MainWindow", "TextLabel"))
        self.Song1Name.setText(_translate("MainWindow", "Song1Name"))
        self.Feature1_1.setText(_translate("MainWindow", "TextLabel"))
        self.Feature2_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "Song name"))
        self.label_8.setText(_translate("MainWindow", "Centroid"))
        self.label_9.setText(_translate("MainWindow", "Bandwidth"))
        self.SecondSongName.setText(_translate("MainWindow", "TextLabel"))
        self.Feature1_2.setText(_translate("MainWindow", "TextLabel"))
        self.Feature2_2.setText(_translate("MainWindow", "TextLabel"))

